# Generated by Django 5.0 on 2025-08-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
